export const ActionTypes = {
  SET_FURNITURE: "SET_FURNITURE",
  SET_ELECTRONICS: "SET_ELECTRONICS",
  SET_FASHION: "SET_FASHION",
  SET_JEWELRY: "SET_JEWELRY",
  SET_BAGS: "SET_BAGS",
  SET_TOYS: "SET_TOYS",
  SET_BEAUTY: "SET_BEAUTY",
  SET_AUTOMOBILE: "SET_AUTOMOBILE",
  SET_FETCH_PRODUCTS_SUCCEEDED_NOTIFICATION:
    "SET_FETCH_PRODUCTS_SUCCEEDED_NOTIFICATION",
};
